### ISSUE TITLE
Roadmap: WaffleServer-Vizabi-VizabiTools

### ISSUE THREAD

**Issue by korel-san** [Gapminder/waffle-server#114]
- [ ] time intervals (`year, month, day, week, querter`) model is supported by neo4j [refs #116]
- [ ] `geo` ('global, region, country, unstate, category') filers is supported by WS [refs #117]
- [ ] `time` and `geo` filters should stay on supported by WS [refs #118]
- [ ] integration tests for /stats and /geo [refs #119, #120]
- [ ] unit tests for /geo (AAA - arrange act assert) [refs #121]
- [x] update winston logging (logging by 1 pushing to log, update version, logging by environment variable) [refs #122]
- [x] clear IndexDb collection for each import [refs #123]
- [ ] update local environment to the dev-stage-prod WS
