### ISSUE TITLE
Roadmap: DDF-csv reader

### ISSUE THREAD

**Issue by buchslava** [Gapminder/waffle-server#115]
- [ ] `time filter` implementation; modification of query to `Vizabi` (by `Vizabi team`) is expected
- [ ] `geo filter` implementation; consideration with `Vizabi team` is expected
- [ ] remove geo hardcode from metadata template
- [ ] create a database/microservice for `Vizabi service data`. I mean next data:
  1. metadata: colors for `geo` and `measures` ...
  2. metadata: charts per indicator or property
  3. metadata: scales for indicator or property
  4. metadata: mapping for indicators tree
  5. query: ui settings
  6. query: state.marker: axis and color settings for indicators
- [ ] UI for `Vizabi service data`
- [ ] `Vizabi Tools DDF-CSV` integration with `Vizabi service data`
