### ISSUE TITLE
Integration tests for /stats

### ISSUE THREAD

**Issue by korel-san** [Gapminder/waffle-server#119]
- [ ] `geo-time` request [refs #124]
- [ ] `geo-props` request [refs #125]
- [ ] `measures` request [refs #126]
