### ISSUE TITLE
RoadMap: Server-render-site

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/waffle-server#127]
- [ ] Vizabi server-side rendering:
  - [x] Configure and embed Vizabi into the html page
  - [x] Vizabi current `state` reflected in the `window.location.hash` should be the same as it is on the `Vizabi Tools Page`
  - [x] Webshot should be able to take screenshots of the Vizabi using Vizabi `state` located in the `window.location.hash`
  - [x] Decrease the amount of time that is needed for a Vizabi screenshot taking (by the Webshot)
  - [ ] Investigate what kind of Vizabi `state` is required by each type of chart (Bubble, Map, Mountain). So that we were able to pull out only that part of the `state` that is needed for screenshot taking.
