### ISSUE TITLE
Roadmap: WaffleServer  

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#128]
- [ ] Cover with tests WS critical parts
- [ ] Documentation for existing WS API (update, add new parts)
- [ ] Translations and metadata should have UI for editing them (of course in here we have question regarding versioning).
- [ ] WS data versioning (both metadata and dimensions, measures, etc.)
- [ ] Serving not all translations and metadata, but only those parts of them, that are used by Vizabi at the moment.
- [ ] Isolate neo4j access in separate service, break stats and all similar services into smaller parts, so that they were more easily tested
- [ ] Currently WS supports only one type of interpolation, but Vizabi requires different types of it for different measures and charts.
- [ ] Do we need custom time intervals like 1,5 years intervals. According to this how time data should be organised in neo4j schema? Even more - this schema should be developed to be flexible and potentially allow us to query different time slices.
- [ ] Deploy and all infrastructure processes should be one-click (I know that guys already working on this)
