### ISSUE TITLE
Global Roadmap

### ISSUE THREAD

**Issue by korel-san** [Gapminder/waffle-server#130]
- [ ] **WS business logic**
  - [ ] File `metadata.json` is obsolete and will be removed, instead:
    1. For `IndicatorsDB` will be created route that should be able to serve metadata per dimension, dimension property, indicator(measure) (SHOULD BE DISCUSSED WITH VIZABI TEAM):
       
       ```
       This asks for one measure(indicator), dimension
       /api/meta?select=geo
       /api/meta?select=geo.link
       ```
       
       and as a possible response:
       
       ```
       {
         "success": true,
         "error": null,
         "data": {
             "link": "https://en.wikipedia.org/wiki/Earth"
         }
       }
       ```
       - [ ] `time` that exists currently in `IndicatorsDB` does really represent `universal_time` which is in turn - https://en.wikipedia.org/wiki/Coordinated_Universal_Time
       - [x] `allowCharts` property in `IndicatorsDb` should not be sent by WS (will be removed by Vizabi - other approach will be used instead to cover this functionality).
       - [x] supporting query select for specified concepts: `/api/meta?select=year,population,country.link`
       - [ ] supporting query language for getting meta from WS: `/api/meta?select=link,tags,name&usability=<=3&type=subdimension`
    2. [x] `Colors section` in metadata.json is still under discussion and can be implemented as a properties for the measure(indicator), dimension. Default colors are also should be discussed (where is an appropriate place for them). As duscussed with Ola - any measure, dimension or entity can have a colour property, but they shouldn't be treated any differently than other properties. There will not be any default colors for a dataset defined in DDF).
    3. [ ] `IndicatorsTree` is also under question, cause it is not clear yet how this will be represented in ddf. This one relates to the `IndicatorsDB` because `IndicatorsTree` describes measure's groups.
    4. [ ] **_NOTE**_ For serving Vizabi specific data we can add special route: `/api/vizabi/meta` which one will be serving colors, IndicatorsTree etc.
  - [ ] WS should support queries that are supposed to ask questions such as: `Do we have values for measure POPULATION for the given dimensions COUNTRY,TIME` (subdimensions also should be supported, though from API perspective there are no difference between `dimensions` and `subdimensions`) [refs #142].
  - [x] **Waffle Server `geo` model issues:**
    - [x] `geo` ('global, region, country, unstate, category') filers should be supported by WS in stats route [refs #117]
    - [x] We need to get rid of geo.cat in queries to WS. It can be resolved via `is--` operator. Usage example: `geo.is--country (geo.is--un_state) | geo.isCountry (geo.isUn_state)`. We should support both: `geo.cat` and `is--` options until Vizabi fully supports `is--` [refs #138].
      `is--` is thus an operator to check if an entity is member of a certain set (like country, un_state, city).
  - [ ] **Waffle Server `universal_time_interval` related issues:**
    - [ ] time intervals (`year, month, day, week, querter`) should be supported by neo4j in stats route [refs #116]
    - [ ] WS should support filtering for time ranges (week, quarter, year, month, day): `{where:{universal_time_interval: ['1800w1', ['2000w30', '2010w20'], '2015w53']}}`
    - [ ] Do we need custom time intervals like 1,5 years intervals. If yes - how time data should be organized in neo4j schema? Even more - this schema should be developed to be flexible and potentially allow us to query different time slices.
  - [ ] **We should come up with a way of flexible translations updating** (SHOULD BE DISCUSSED WITH CONTENTFUL TEAM)
  - [ ] **WS data versioning (both metadata and dimensions, measures, translations, etc). Neo4j schema should be probably changed so this issue by itself might become huge epic.**
  - [ ] It would be very helpful if WS supported following feature - When updating DDF repo on github WS gets notified and imports changed values automatically (it imports changed files to the target environment (dev, stage, prod) reasoning against which branch was modified in repo: dev, stage, master accordingly).
    **_Note:**_ This feature depends on `versioning feature` and will be done as soon as former will be implemented.
  - [ ] Currently WS supports only one type of interpolation, but Vizabi requires different types of it for different measures and charts.
  - [ ] Documentation for existing WS endpoint API should be improved (update existing one, add new sections)
    **_Note:**_ We can adopt following approach https://github.com/OAI/OpenAPI-Specification
  - [ ] In a collaboration with the Vizabi team we should come up with a requirements to the WS server UI.
- [ ] **WS refactorings**
  - [x] Clear IndexDb collection for each import [refs #123]
  - [ ] Neo4j related functionality should be encapsulated into separate service (increasing modularity and enforcing SRP).
  - [ ] Break stats and all similar services into smaller parts, so that they were more easily tested (it will enforce SRP).
- [ ] **WS infrastructure**
  - [x] Change all login/passwords for dev|stage|prod (mongo/neo4j)
  - [x] Update winston logging (batch logging, update winston version, logging should be flexibly configurable) [refs #122]
  - [x] Add logging for import/export with the same sittings as for the WS
  - [ ] Local development environment should reflect dev-stage-prod environments (tools versions etc.)
  - [ ] Update all needed global environments (dev|stage|prod) according to the [wiki](https://github.com/gapminder/waffle-server/wiki/Global-environment)
  - [ ] **CI, CD**
    - [ ] We should have a script for `one-click` deployment
    - [x] We should have a script for `one click` release [refs #131]:
      - [x] version in package.json should be bumped
      - [x] CHANGELOG.md should be generated automatically using git tags and commits
      - [x] all release-specific stuff (changlelog, package.json) should be merged back into development branch
    - [ ] After every `git push` - tests should run against appropriate branch on CI server [private repo](https://github.com/valor-software/ci-tools)
    - [x] Changelog for each release should be generated automatically using commit history [refs #131]
  - [ ] **WS test coverage**
    - [x] integration tests for /stats and /geo [refs #119, #120]
    - [x] unit tests for /geo [refs #121]
    - [ ] ddf importing/exporting should have smoke tests, so that one who did the importing/exporting was sure that process went well.
    - [ ] queries that are served `time` and `geo` should stay untouched and their spec should be enforced in tests [refs #118]
    - [ ] load testing
- [ ] **Security Issues**, [details](https://blog.liftsecurity.io/2012/12/07/writing-secure-express-js-apps)
  - [ ] Injection Vulnerabilities (express, neo4j, mongodb)
  - [ ] Session fixation and hijacking
  - [ ] Cross-Site Vulnerabilities (Scripting, Request Forgery: [csrf](http://www.senchalabs.org/connect/csrf.html), [helmet](https://github.com/evilpacket/helmet))
  - [ ] Mass Assignment
- [ ] **Vizabi readers**
  - [ ] Time query that comes to Readers should comply to the spec, described in https://gist.github.com/korel-san/f45894e0685c5c28807b [refs https://github.com/valor-software/vizabi-tools-ddf-csv-reader/issues/1]
  - [ ] Geo query that comes to Readers should be discussed with Vizabi team. Implementation - TBD.
- [x] **Vizabi server-side rendering**
  - [x] Configure and embed Vizabi into the html page
  - [x] Vizabi current `state` reflected in the `window.location.hash` should be the same as it is on the `Vizabi Tools Page`
  - [x] Webshot should be able to take screenshots of the Vizabi using Vizabi `state` located in the `window.location.hash`
  - [x] Decrease the amount of time that is needed for a Vizabi screenshot taking (by the Webshot)
  - [x] Investigate what kind of Vizabi `state` is required by each type of chart (Bubble, Map, Mountain). So that we were able to pull out only that part of the `state` that is needed for screenshot taking.
