### ISSUE TITLE
Vizabi suggestions service (aka "Magic" feature)

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#149]
- [ ] Implementation of rule processor (refs #150)
- [ ] Expose WS endpoint for serving vizabi suggestions (refs #151)
- [ ] Expose WS endpoint for taking screenshots of vizabi charts using given vizabi state (refs #152)
- [ ] Vizabi suggestions service frontend and backend integration (refs #153)
- [ ] Vizabi model investigation (for detecting ability to turn on "magic" feature) (refs #154)
- [ ] Implementation of "Parents when non selected" rule (refs #155)
- [ ] Implementation of "Parent when one selected" rule (refs #156)
- [ ] Implementation of "Parents when 2 to 4 selected" rule (refs #157)
- [ ] Implementation of "Children of selected" rule (refs #158)
- [ ] Implementation of "Linechart to map when is count-measure" rule (refs #159)
- [ ] Implementation of "Linechart to map when is non-rate-measure" rule (refs #160)
- [ ] Implementation of "Linechart to bubble-chart when is count-measure" rule (refs #161)
- [ ] Implementation of "Linechart to bubble-chart when is non-rate-measure" rule (refs #162)
- [ ] Implementation of UI part for vizabi suggestions service (refs #163)
  - [ ] Show generated vizabi suggestions in the 'Related section' (refs #164)
  - [ ] Implementation of applying new vizabi state using generated suggestion via without page reloading. (refs #165)
  - [ ] Implementation of subscription for generated vizabi suggestion from WS (refs #166)
  - [ ] Implementation of vizabi suggestions rendering for the BubbleMap chart (refs #167)
  - [ ] Implementation of vizabi suggestions rendering for the Bubble chart (refs #168)
  - [ ] Implementation of vizabi suggestions rendering for the Mountain chart (refs #169)
