### ISSUE TITLE
Implement transaction support (transaction state machine (in progress, done, broken))

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#265]
- [x] Implement transaction's rollback #264
- [x] It should be impossible to query data by version with broken transaction #263
- [x] Implement endpoint on WS to serve transactions' state #266
- [x] Implement endpoint on WS to initiate rollback #267
- [ ] Integrate WS and WS CLI transaction flow #270
