### ISSUE TITLE
WS CLI - WS authentication support

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#275]
- [x] Investigate auth approach for WS CLI to WS #271
- [x] Implement auth on WS CLI #272
- [x] Implement auth on WS #273
- [ ] Integrate WS and WS CLI auth flow #274
