### ISSUE TITLE
WS CLI improvements

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#281]
- [ ] research and implement long polling requests #276
- [x] implement lib for git flow #277
- [x] research input handling while interface is locked #278
- [x] implement new ws response format, error handling #279
- [x] implement new flow to check dataset state #280
- [x] Implement step in WS CLI to observe transactions' state #268
- [x] Implement step in WS CLI to initiate rollback for given transaction #269
