### ISSUE TITLE
Implement new succinct response format for WS endpoints (less traffic, higher performance)	

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#289]
- [x] Investigate how we can reduce amount of data transfered #258
- [x] discuss new reponse format with Vizabi team - what kind an inpact will it have on Vizabi #283
- [x] investigate how WS reader in Vizabi should be modified according to new reponse format #284
- [x] implement support of new reponse format by WS reader in Vizabi #285
- [x] apply new response format for concepts endpoint #286
- [x] apply new response format for entities endpoint #287
- [x] apply new response format for datapoints endpoint #288
