### ISSUE TITLE
Demo preparation

### ISSUE THREAD

**Issue by rychkog** [Gapminder/waffle-server#294]
- [x] write demo flow #291
- [x] prepare stub data #292
- [x] validate demo flow #293
